project:
  type: website
execute:
  echo: false
  warning: false
  error: false
website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hamgamb
      - icon: linkedin
        href: https://www.linkedin.com/in/hamish-gamble-b8b450b5/
format:
  html:
    theme: cosmo
    css: styles.css
    fig-width: 6
    fig-asp: 0.618




